### DISCUSSION TITLE
相关的 Github Action

### DISCUSSION THREAD

**Discussion by zjp-CN** [os-checker/os-checker#7] [Ideas]
### fork/sync 仓库

* [aormsby/Fork-Sync-With-Upstream-action](https://github.com/aormsby/Fork-Sync-With-Upstream-action) 将 forked 的仓库与上游仓库同步
* 自动 fork 仓库

```yaml
name: Fork Repository

on: [schedule]  # 或者其他触发条件

jobs:
  fork-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Fork the repository
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/ORIGINAL_OWNER/ORIGINAL_REPO/forks
```

### 缓存

* [actions/cache](https://github.com/actions/cache) 缓存编译工件或者任何文件
* [缓存本地 docker 镜像示例](https://docs.docker.com/build/ci/github-actions/cache/#local-cache)
  * [官方阿里云服务器 docker 使用说明](https://help.aliyun.com/zh/ecs/use-cases/install-and-use-docker-on-a-linux-ecs-instance)

```yaml
name: Docker Build & Deploy

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

* ~~[rustup docker 镜像](https://hub.docker.com/r/rustdocker/rustup/tags)：（不知道是否官方维护）由于很多时候会固定 rustc 的版本号，所以需要通过 rustup 安装它们~~
* [rustlang/rust](https://hub.docker.com/r/rustlang/rust/)：官方维护的夜间工具链；由于内核代码使用较多 nightly features，fmt/clippy 之类的代码主要用最新的夜间版本
  * 更多使用说明参见 <https://hub.docker.com/_/rust/>
  * `docker pull rustlang/rust:nightly`

### 其他

* [buhenxihuan/Starry/auto_test.yml](https://github.com/buhenxihuan/Starry/blob/x86_64/.github/workflows/auto_test.yml)：利用 pytest 和 allure 报告测试结果
  * <https://buhenxihuan.github.io/Starry/>：静态网页部署示例
  * [kern-crates/testing](https://github.com/kern-crates/testing)：测试脚本仓库
