### ISSUE TITLE
RAP 错误地处理项目布局

### ISSUE THREAD

**Issue by zjp-CN** [os-checker/os-checker#140]
```toml
[package]
name = "os-checker"

[workspace]
exclude = ["repos/**"]
members = ["os-checker-types", "os-checker-database"]
```

```rust
// pkg_name=os-checker, checker=Rap
// toolchain=nightly-x86_64-unknown-linux-gnu, target=x86_64-unknown-linux-gnu
// pkg_dir=/home/runner/check/repos/os-checker/os-checker
// cmd=cargo +nightly-2024-06-30 rap -F
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 33.61s
error: no bin target named `os-checker-database`.
Available bin targets:
    os-checker

12:08:54|RAP|ERROR|: Finished with non-zero exit code.
```
