### ISSUE TITLE
确定一个代码库的目标架构的步骤

### ISSUE THREAD

**Issue by zjp-CN** [os-checker/os-checker#26]
据我所知，从 rustc/cargo 角度来看，指定目标架构 (target triple) 从高到低的优先级为：
1. 命令行参数传递 `--target`
2. `RUSTFLAGS` （不确定是否适合用于指定 target，大部分情况下指定 `-C`、`-Z` 和 `--cfg`）
3. `.cargo/config.toml` 中的 `[build] target = ...`
4. 如果以上都没有指定，则使用 rustup 的默认的工具链[^1]

[^1]: 通过 `rustup default` 可知，但最好由 `rustc -Vv | grep host | sed "s/host: //"` 查询，因为前者可能会报告带夜间和日期的工具链名称，比如 `nightly-x86_64-unknown-linux-gnu` 或者 `nightly-2024-08-10-x86_64-unknown-linux-gnu`，但后者不会带这些前缀，也不受 rust-toolchain 的影响

然而，从 os-checker 的角度看，确定目标架构从高到低的优先级应为：
1. `cargo check -vv` 会打印编译所有 crates 的命令 ( 一些细节见 [#25](https://github.com/os-checker/os-checker/issues/25#issuecomment-2295156224) )，抽取当前 package（或者 crates ）上的命令
    * 如果由上面的 1-3 条架构指定情况，则命令内会出现 `--target`，那么得到默认的 target triple 列表
    * 如果没有任何地方指定，则命令内无 `--target`，那么默认使用 `rustup default` 或者 打印的 target triple（对于 WebUI，由于 docker 运行环境为 x86-64，那么为 `x86_64-unknown-linux-gnu`）
2.  如果 os-checker YAML 配置文件出现自定义命令
    * 如果包含 --target 参数，则不考虑 1 得到的默认 target triple 列表
    * 如果不包含 --target 参数，则强制加上默认 target triple 列表
3. os-checker 会启发式搜索一些常见的脚本来猜测额外的目标架构信息，这些被查询脚本为：`.github` 文件夹内的任何文件、递归查找 Makefile、makefile、py、sh、just 后缀的文件
    * 如果这些脚本包含 `rustc --print target-list` 罗列的 traget triple，那么将它 **增加到** 第 1 步的 `cargo check -vv` 得到列表上
    * 注意：这些脚本暂不考虑 package 级别，也就是说，一旦一个 traget triple 被搜索到，那么它将适用于该仓库内的所有 package
    * 注意：这种启发式搜索显然非常粗糙，但是目前我没有计划对此进行更精细地调整

**Comment by zjp-CN** [comment]
作为额外的背景，我观察到 docs.rs 是按照如下方式处理编译目标架构的：

docs.rs 有自己的配置信息，即 Cargo.toml 中的 [`[package.metadata.docs.rs]`](https://docs.rs/about/metadata) 表：

```toml
[package.metadata.docs.rs]
# Target to test build on, used as the default landing page (default: "x86_64-unknown-linux-gnu")
#
# Any target supported by rustup can be used.
default-target = "x86_64-unknown-linux-gnu"

# Targets to build (default: see below)
#
# Any target supported by rustup can be used.
#
# Default targets:
# - x86_64-unknown-linux-gnu
# - x86_64-apple-darwin
# - x86_64-pc-windows-msvc
# - i686-unknown-linux-gnu
# - i686-pc-windows-msvc
#
# Set this to `[]` to only build the default target.
#
# If `default-target` is unset, the first element of `targets` is treated as the default target.
# Otherwise, these `targets` are built in addition to the default target.
# If both `default-target` and `targets` are unset,
#   all tier-one targets will be built and `x86_64-unknown-linux-gnu` will be used as the default target.
targets = ["x86_64-apple-darwin", "x86_64-pc-windows-msvc"]
```

实际上，如果一个发布到 crates.io 的库不写 `[package.metadata.docs.rs]`，那么 docs.rs 会在默认的那 5 个目标架构上构建，如果构建成功，则表明支持该架构，如果失败，则不支持。（仅仅是我猜测的，真正要确认这个需要问一下 docs.rs team，但我并不怎么关心这个）

![截图_20240819212335](https://github.com/user-attachments/assets/405524e0-72a7-4999-9ac0-0d7d82dda970)


这也不是完美的，因为它会带来 false negative，比如
* serde_json 的 Cargo.toml 显式只指定 `x86_64-unknown-linux-gnu`，这导致 docs.rs 只显示一个 triple，但是它其实可以在其他平台上正常使用
![截图_20240819213000](https://github.com/user-attachments/assets/1092cd10-17a2-44ac-8156-57cf3b0903b1)
* tokio 并未在 Cargo.toml 中指定任何架构，它可以在 Windows 上使用，但可能指定了编译标志，导致只在类 unix 平台上成功（我猜测）
![截图_20240819212939](https://github.com/user-attachments/assets/7bda2d58-44b7-4eb5-9249-1ecc79c08626)


---

docs.rs 的方式不太适用于 os-checker，因为它容许排除构建错误的平台，但 os-checker 不容许这样。
