### ISSUE TITLE
Targets: 考虑识别每个 package Cargo.toml 的 metadata.os-checker 表来覆盖 metadata.docs.rs 的行为

### ISSUE THREAD

**Issue by zjp-CN** [os-checker/os-checker#33]
在 https://github.com/os-checker/os-checker/issues/26 中，目前仅有的覆盖 targets 的行为是在 os-checker 的 YAML 配置文件中，使用含 `--target`  的自定义检查命令。

[metadata 表](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table) 专门用来存储 package 或者 workspace 的其他信息，供某些工具识别：

> The package.metadata table, however, is completely ignored by Cargo and will not be warned about. This section can be used for tools which would like to store package configuration in Cargo.toml.

如果支持 metadata.os-checker，那么如何与 metadata.docs.rs 的行为交互？

由于现在在 metadata.docs.rs 中指明 targets 并不常见，似乎可以完全不考虑它，而只读取 metadata.os-checker，但可以借鉴

```toml
[package.metadata.os-checker]
# 为了简单，不支持非数组，即不支持 target = "x86_64-unknown-linux-gnu"
targets = ["x86_64-apple-darwin", "x86_64-pc-windows-msvc"] 

# 一些自定义检查工具命令：比如指定其他编译条件、设置编译环境等等
# 这些检查命令不限任何功能，只要是 shell 命令即可
clippy = [
  "cargo clippy --features ...", # 设置 features
  "cargo clippy --features ... --test ...", # 检查非 lib/bin crates
  "cargo clippy --target ...", # 设置特定 target
  "RUSTFLAGS=\"--cfg=...\" cargo clippy --target ...", # 设置 RUSTFLAGS
  "apt install ...lib; wget ...; cargo clippy", # 设置编译环境
]
```
