### ISSUE TITLE
Bug: slab_allocator Cargo.toml 中重复定义 keywords

### ISSUE THREAD

**Issue by zjp-CN** [os-checker/os-checker#48]
目标仓库：https://github.com/kern-crates/slab_allocator
CI：https://github.com/os-checker/os-checker/actions/runs/10685223435/job/29617510934
解决方式：记录到 Cargo 错误类别

```toml
keywords = ["Starry"]
keywords = ["slab", "allocator", "no_std", "heap", "kernel"]
```

```rust
Caused by:
    无法读取 cargo metadata 的结果：`cargo metadata` exited with an error: error: duplicate key `keywords` in table `package`
     --> slab_allocator/Cargo.toml:9:1
      |
    9 | keywords = ["slab", "allocator", "no_std", "heap", "kernel"]
      | ^
      |
Location:
    src/layout/mod.rs:58:28
```
