### ISSUE TITLE
cackle: ACL 代码检查器

### ISSUE THREAD

**Issue by zjp-CN** [os-checker/os-checker#97]
地址：https://github.com/cackle-rs/cackle

> Cackle is a tool to analyse the transitive dependencies of your crate to see what kinds of APIs each crate uses.

> The idea is look for crates that are using APIs that you don't think they should be using. For example a crate that from its description should just be doing some data processing, but is actually using network APIs.

```toml
[api.process]
include = [
    "std::process",
]
exclude = [
    "std::process::abort",
    "std::process::exit",
]

[common]
version = 2
```

```rust
$ cat src/main.rs
fn main() {
    duct::cmd!("echo", "hi").run().unwrap();
}

$ cat Cargo.toml
[dependencies]
duct = "0.13.7"
```

![6ec2a1e9c8a5aff98a0208cb5be2df0](https://github.com/user-attachments/assets/32031bbb-5460-4de9-a128-401fd3827889)

不过，貌似它是一个 TUI 工具，再加上必须编写配置文件，不太方便集成到 os-checker。
